version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    
    environment:
      POSTGRES_DB: mon_application_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

    secrets:
      - db_password

    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d mon_application_db"]
      interval: 10s
      timeout: 5s
      retries: 5

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 512M 

    networks:
      - database

volumes:
  postgres_data:
    driver: local

secrets:
  db_password:
    file: ./secrets/db_password.txt
    
networks:
  database:
    driver: bridge
    internal: true
